---
abstract: 'Locale::Maketext::TieHash::quant - Tying method quant to a hash'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Cwd: 0
  Locale::Maketext: 1.17
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Simple: 0
  parent: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Maketext-TieHash-quant
provides:
  Locale::Maketext::TieHash::quant:
    file: lib/Locale/Maketext/TieHash/quant.pm
    version: 0.06
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  English: 0
  Params::Validate: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
